CREATE TABLE EMP_TEMP (
  EMP_ID NUMBER,
  EMP_EMAIL VARCHAR2(40)
);

DECLARE
  NUMBER_OF_EMP NUMBER;
BEGIN
  SELECT COUNT(EMP_ID) INTO NUMBER_OF_EMP FROM EMP_TEMP;
  
  FOR I IN 1 .. NUMBER_OF_EMP LOOP
    INSERT INTO EMP_TEMP (EMP_ID, EMP_EMAIL) VALUES (I, 'NOT AVAILABLE NOW');
  END LOOP;
END;
